"""
Deterministic question generation templates (spec Section 17).

"Question generation should initially be deterministic. Do not require
an LLM. Use controlled templates based on: topic, Bloom level,
difficulty, marks."

Every template string below is taken directly from the spec's own
worked examples for each Bloom level. Where a Bloom level has more than
one template, selection between them is deterministic (an MD5 hash of
the request's own topic/difficulty/marks, never Python's randomized
`hash()` or the `random` module) -- calling this twice with the exact
same request always produces the exact same question text.
"""

from __future__ import annotations

import hashlib
from typing import Dict, List, Optional

# Templates grouped by Bloom level. "{topic}" is always filled from the
# request's `topic`. The two-topic ANALYZE template additionally needs
# `topicB` -- see `render_question` for the fallback when it's absent.
BLOOM_TEMPLATES: Dict[str, List[str]] = {
    "remember": [
        "Define {topic}.",
        "List the major types of {topic}.",
        "State the core principles behind {topic}.",
        "Identify the key components of {topic}.",
        "What are the primary characteristics of {topic}?",
        "Enumerate the standard steps in {topic}.",
        "Name the essential prerequisites for studying {topic}.",
        "Outline the main advantages of {topic}.",
        "Recall the foundational terminology used in {topic}.",
        "Which metrics are commonly used to measure {topic}?",
    ],
    "understand": [
        "Explain {topic} with a suitable example.",
        "Describe how {topic} works.",
        "Distinguish between theoretical principles and practical execution in {topic}.",
        "Summarize the workflow involved in {topic}.",
        "Clarify the main reasons for using {topic} in practice.",
        "Illustrate the role of data in {topic}.",
        "Discuss how environmental factors affect {topic}.",
        "Explain why {topic} behaves differently under varying conditions.",
        "Interpret the common outputs generated by {topic}.",
        "Elaborate on the significance of {topic} in computer science.",
    ],
    "apply": [
        "Given the following scenario, explain how {topic} could be applied.",
        "Demonstrate how to implement {topic} to solve an engineering problem.",
        "Illustrate the application of {topic} in automated decision making.",
        "Construct a step-by-step procedure applying {topic} to tabular datasets.",
        "How would you use {topic} to improve processing speed in an application?",
        "Show how {topic} can be adapted to handle missing or corrupt data.",
        "Apply the concepts of {topic} to build a predictive workflow.",
        "Develop an execution plan using {topic} within a cloud architecture.",
        "Apply {topic} to optimize resource allocation in a network.",
        "Formulate a practical calculation demonstrating the utility of {topic}.",
    ],
    "analyze": [
        "Compare {topic} and {topicB}.",
        "Analyze the effect of {topic} on {topicB}.",
        "Contrast the architectural principles of {topic} versus {topicB}.",
        "Examine the primary trade-offs between {topic} and {topicB}.",
        "In what scenarios would you choose {topic} over {topicB}?",
        "Analyze the performance and efficiency differences between {topic} and {topicB}.",
        "How do data requirements differ between {topic} and {topicB}?",
        "Investigate how the integration of {topic} impacts the behavior of {topicB}.",
        "Highlight the core advantages of {topic} compared to {topicB}.",
        "Deconstruct the operational differences when deploying {topic} versus {topicB}.",
    ],
    # ANALYZE fallback when the request has no second topic to compare
    # against -- still a genuine analysis prompt, just single-topic.
    "analyze_single_topic": [
        "Analyze the key components of {topic} and how they relate to each other.",
        "Deconstruct {topic} into its functional subsystems and examine their interactions.",
        "Examine the computational bottlenecks and performance limitations in {topic}.",
        "Investigate the impact of parameter tuning on {topic}.",
        "Analyze the difference between high-bias and high-variance regimes in {topic}.",
        "Break down the risk factors and failure modes of {topic}.",
        "Inspect the data pipeline requirements necessary for {topic}.",
        "Compare the computational complexity across different implementations of {topic}.",
        "Analyze how feature selection influences the behavior of {topic}.",
        "Audit the trade-offs between speed and accuracy inherent in {topic}.",
    ],
    "evaluate": [
        "Evaluate the suitability of {topic} for the given problem scenario.",
        "Critique the reliability and robustness of {topic} in production.",
        "Assess the ethical and privacy considerations surrounding {topic}.",
        "Judge the effectiveness of {topic} compared to heuristic baselines.",
        "Defend or refute the necessity of adopting {topic} in resource-limited devices.",
        "Appraise the scalability of {topic} as data volume grows exponentially.",
        "Evaluate the error margins and tolerance thresholds in {topic}.",
        "Weigh the cost-benefit trade-offs of deploying {topic}.",
        "Determine whether {topic} satisfies enterprise-grade latency constraints.",
        "Review and critique recent benchmarks published for {topic}.",
    ],
    "create": [
        "Design a solution using {topic} for the given problem.",
        "Formulate an innovative pipeline that incorporates {topic} for streaming data.",
        "Construct a novel architectural framework based on {topic}.",
        "Propose an original hybrid approach combining {topic} with heuristic search.",
        "Develop a specialized testing harness tailored for validating {topic}.",
        "Synthesize an automated fault-recovery mechanism into {topic}.",
        "Design an end-to-end prototype leveraging {topic} for smart diagnostics.",
        "Create a modular abstraction layer that integrates {topic} with legacy systems.",
        "Formulate a mathematical formulation to extend the capabilities of {topic}.",
        "Draft a specification for an open-source library implementing {topic}.",
    ],
}

BASE_COUNTS: Dict[str, int] = {
    "remember": 2,
    "understand": 2,
    "apply": 1,
    "analyze": 2,
    "analyze_single_topic": 1,
    "evaluate": 1,
    "create": 1,
}


def _deterministic_index(seed_text: str, modulus: int) -> int:
    """Deterministic (never random, never Python's hash-randomized
    built-in `hash()`) pseudo-index into a template list, so the same
    request always selects the same template."""
    digest = hashlib.md5(seed_text.encode("utf-8")).hexdigest()
    return int(digest, 16) % modulus


def render_question(
    topic: str,
    bloom_level: str,
    difficulty: str,
    marks: float,
    topic_b: Optional[str] = None,
    variant_index: Optional[int] = None,
) -> str:
    """
    Renders question text for a single (topic, bloomLevel, difficulty,
    marks[, topicB, variantIndex]) request. Deterministic: identical arguments always
    produce identical text. When variant_index is provided, picks a unique
    template variant to avoid generating duplicates when quantity > 1.
    """
    bloom_key = bloom_level.lower()

    if bloom_key == "analyze" and not topic_b:
        key = "analyze_single_topic"
    else:
        key = bloom_key

    templates = BLOOM_TEMPLATES.get(key)
    if not templates:
        raise ValueError(f"No question templates defined for Bloom level '{bloom_level}'.")

    second_topic = topic_b or ""
    seed = f"{topic}|{second_topic}|{bloom_key}|{difficulty}|{marks}"
    if variant_index is None:
        base_count = BASE_COUNTS.get(key, len(templates))
        idx = _deterministic_index(seed, base_count)
    else:
        base_idx = _deterministic_index(seed, len(templates))
        idx = (base_idx + variant_index) % len(templates)

    return templates[idx].format(topic=topic, topicB=second_topic)
